package net.emdal

import kotlin.system.measureTimeMillis


fun main() {
    measureTimeMillis {
        net.emdal.day1.puzzle1.PuzzleSolution().printSolution()
        net.emdal.day1.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day2.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day2.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day3.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day3.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day4.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day4.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day5.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day5.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day6.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day6.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day7.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day7.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day8.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day8.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day9.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day9.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day10.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day10.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day11.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day11.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day12.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day12.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day13.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day13.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day14.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day14.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day15.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day15.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day16.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day16.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day17.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day17.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day18.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day18.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day19.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day19.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day20.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day20.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day21.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day21.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day22.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day22.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day23.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day23.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day24.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day24.puzzle2.PuzzleSolution().printSolution()
//        net.emdal.day25.puzzle1.PuzzleSolution().printSolution()
//        net.emdal.day25.puzzle2.PuzzleSolution().printSolution()
    }.let {
        println("Total runtime of all advent of code jobs: $it milliseconds.")
    }
}